### ISSUE TITLE
make -V UNIQUENAME does not work, script does not get name of port

### ISSUE THREAD

**Issue by UlasSAYGINIM** [curana/makextract#2]
hi,
i tested your script with FreeBSD 13 but i couldnt get portnames,
it creates options on UNSET section but not showing portname.
i tested make -V UNIQUENAME command on commandline , it does not show port name.
because of this, script does not work properly.

can you check?

**Comment by UlasSAYGINIM** [comment]
https://forums.freebsd.org/threads/options_name-_options_set-in-make-conf-not-working.65995/

make -V OPTIONS_NAME seem working i will update and try.

**Comment by curana** [comment]
Thanks for reporting.

I need to have a look into it. I didn't use this script for a long time now.
If you have a fix, I would be happy to implement it.
